### ISSUE TITLE
Interactive mean plot question

### ISSUE THREAD

**Issue by StePhanino** [LumiSpy/lumispy-demos#12]
Dear all, 
I have a question on the interactive ROI plot in the example `01_EnergyConversion_GaussianFitting.ipynb`. 
This is the code:

    im = cl_sem.T
    im.plot()
    roi1 = hs.roi.SpanROI(left=455, right=485) #sets a digitalbandfilter
    im_roi1 = roi1.interactive(im, color="red")
    im_roi1_mean = hs.interactive(im_roi1.mean,
                          event=roi1.events.changed,
                          recompute_out_event=None)
    im_roi1_mean.plot(cmap='viridis')

The `im_roi1_mean.plot(cmap='viridis')` plot is supposed to be updated whenever the span is changed by the user on the `im.plot()`?

I'm using jupyter notebook with the option `%matplotlib qt`, with Python 3.10.4.

thanks a lot,

stefano

**Comment by jlaehne** [comment]
Good question @StePhanino . At least, it behaves the same for me.

It is an upstream issue as the functionality is provided by HyperSpy. I would propose asking the question in the gitter chat:
https://gitter.im/hyperspy/hyperspy

Depending on the answer there, you could then create an issue in the hyperspy repositorium:
https://github.com/hyperspy/hyperspy

**Comment by jlaehne** [comment]
Possibly related to https://github.com/hyperspy/hyperspy/issues/2950 , then it should be fixed in the development branch by https://github.com/hyperspy/hyperspy/pull/2952

**Comment by jlaehne** [comment]
Indeed, it is working with the [RELEASE_next_patch](https://github.com/hyperspy/hyperspy/tree/RELEASE_next_patch) branch of HyperSpy. Thus, should be fixed also on pip/conda once [v1.7.1](https://github.com/hyperspy/hyperspy/milestone/47) is released.
